on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List directories in the repository
        run: |
          echo "Listing top-level directories:"
          ls -la
          echo "Navigating into the repository folder and listing contents:"
          cd ${{ github.workspace }}
          ls -la
          
      - name: Copy file via SSH password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: 'root'
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{secrets.PASSPHRASE}}
          port: ${{ secrets.PORT }}
          debug: true
          source: "."
          target: /root/next

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: 'root'
          passphrase: ${{secrets.PASSPHRASE}}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            ls
            cd next
            docker compose up --build -d
